### ISSUE TITLE
Document use of CatchOthers with Views

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-javascript-sdk#108]
From @sean-walsh:
This should be documented for proto and the view impl.

For example, I have a view that only utilizes 2 of many events and the others are ignored. Anything that subscribes to an event sourced entity may need a CatchOthers.

**Comment by rstento** [comment]
If an example exists with CatchOthers in it, this should be a simple matter of pulling it into the doc.

**Comment by rstento** [comment]
The example that has CatchOthers isn't in the context of a view. To complete this ticket, we need CatchOthers to be added to the existing View example.

**Comment by sean-walsh** [comment]
Here is an example:

https://github.com/lightbend-labs/akkaserverless-wirelessmesh-java/blob/main/src/main/java/wirelessmesh/domain/CustomerLocationView.java

**Comment by rstento** [comment]
Thanks @sean-walsh, the problem is that I need the example to be in the examples in this repo so that I can include it and it gets validated.

**Comment by sean-walsh** [comment]
Ah sorry!

**Comment by pvlugter** [comment]
Updated the sample used for views in #150 (similar to changes for Java sample in https://github.com/lightbend/akkaserverless-java-sdk/pull/194).
