### ISSUE TITLE
Use consistent proto file naming convention

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-javascript-sdk#112]
@rstento commented on [Thu Jul 08 2021](https://github.com/lightbend/akkaserverless-java-sdk/issues/129)

@mckeeh3 commented on [Mon Jun 07 2021](https://github.com/lightbend/akkaserverless-docs/issues/639)

In the [Writing gRPC descriptors](https://docs.akkaserverless.dev/java-services/proto.html) section of the docs, the proto file naming convention is inconsistent with other parts of the documentation. 

Use "API" and "domain" suffixes for proto file names. Also, use dash versus underscore in file names. 

Examples
* shopping-cart-api.proto
* shopping-cart-domain.proto

**Comment by patriknw** [comment]
According to the style guide https://developers.google.com/protocol-buffers/docs/style:

> Files should be named lower_snake_case.proto

**Comment by rstento** [comment]
I confirmed that this has been fixed in the doc, probably as part of another PR.
