### ISSUE TITLE
Use consistent proto file naming convention in JS value entities

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-javascript-sdk#114]
@mckeeh3 commented on [Mon Jun 07 2021](https://github.com/lightbend/akkaserverless-docs/issues/641)

In [Implementing Value Entities in JavaScript](https://docs.akkaserverless.dev/js-services/value-entity.html) change proto file names to either `shopping-cart-api.proto` or `shopping-cart-domain.proto`. 

---

@rstento commented on [Mon Jun 07 2021](https://github.com/lightbend/akkaserverless-docs/issues/641#issuecomment-856185960)

@mckeeh3, this page has already changed (PR in progress) because the code generation tools have changed and this page is bing updated to use the counter Value Entity example from code gen by @andreaTP. Hugh, please take a look at #633, it is now using the convention of <entity-name>-api or <entity-name>-domain.

---

@rstento commented on [Thu Jul 08 2021](https://github.com/lightbend/akkaserverless-docs/issues/641#issuecomment-876601493)

This still isn't consistent, some examples use _ as the separator, others - and the Event Sourced entity page isn't using the service name in the proto file name.

**Comment by patriknw** [comment]
According to the style guide https://developers.google.com/protocol-buffers/docs/style:

> Files should be named lower_snake_case.proto

**Comment by rstento** [comment]
In the samples directory, it looks like all examples are using the style referenced by @patriknw in the previous comment. The page referenced in the initial issue has been fixed. https://docs.akkaserverless.dev/js-services/proto.html still needs to be fixed using the convention and importing from the samples director. However, we don't have a plain shopping cart proto example, we have a value entity and an event sourced entity cart example. The proto overview page could be updated with both, using tabs or we could pick one.

**Comment by thothmoses** [comment]
@rstento Hmm, I'm feeling a bit of an idiot. I know I'm missing something. - I have looked at the page to be fixed ( https://docs.akkaserverless.dev/js-services/proto.html  ) and I don't see anything that needs to be fixed with respect to this issue. The proto files are all referenced using lower_snake_case, and all the source is being pulled via include from the examples - shoppingcart_api.proto and shoppingcart_domain.proto respectively. Please advise.

**Comment by rstento** [comment]
@thothmoses, you're right. Guess I was looking at something old. Someone must have fixed this and not closed the issue. The only thing that I notice now is that the page doesn't tell the reader that the example used is of a Value Entity.  Something that might be interesting to a reader is to see the difference between a proto file for a Value and an Event Sourced entity.

**Comment by thothmoses** [comment]
Ok - I will add that and close this issue - thx
