### ISSUE TITLE
Add example API proto file to Implementing Event Sourced Entities in JavaScript

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-javascript-sdk#117]
@mckeeh3 commented on [Fri Jun 11 2021](https://github.com/lightbend/akkaserverless-docs/issues/679)

Add an example API proto file tp [Implementing Event Sourced Entities in JavaScript](https://docs.akkaserverless.dev/js-services/eventsourced.html). 

For each component linked to an API, implementing or creating documentation should include a sample API proto file. This will help to make the page more self-contained. Developers that reference one of these pages will not need to look for examples on other pages. 

The content should help readers understand the input, process, and output flow of components. Input is defined in the API proto. Output is defined in the domain proto file. Processing is defined in the component code examples.

**Comment by ennru** [comment]
Outdated.
