### ISSUE TITLE
The generated TS types are broken in the latest release

### ISSUE THREAD

**Issue by janory** [lightbend/akkaserverless-javascript-sdk#134]
In the latest version of the SDK the TS types which we are generating based on the JSDoc annotations got broken.
This has probably happened, because we did some bigger changes, for example removed the `Entity` interface.

It would be nice if we could somehow lint the generated types as part of releasing process in the future, to avoid releasing borken types silently.

Tagging @rstento and @tsonny, because this might has an impact on the generated API Docs pages as well.
Since it's also based on the JSDoc annotations.

**Comment by pvlugter** [comment]
We'll start having more SDK usage compiled with TypeScript. We'll start adding samples and doc examples in TypeScript. We could also have a TypeScript version of the TCK implementation, as that exercises various APIs beyond what the samples use.
