### ISSUE TITLE
Add Replicated Entity page back to JavaScript SDK doc pages

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-javascript-sdk#146]
This task is to bring back the old documentation on replicated entities, but the content still needs to be updated to reflect the new implementation.

**Comment by pvlugter** [comment]
And waiting for some more changes to be merged for the updated implementation (#135, which depends on a proxy release with https://github.com/lightbend/akkaserverless-framework/pull/803).

**Comment by tsonny** [comment]
See Java twin for work details

**Comment by rstento** [comment]
Closing this because the implemention is not complete yet. And, it has changed so much, it makes more sense for the developers to create the first draft instead of reusing the old one.
