### ISSUE TITLE
Support async handlers for entities as well

### ISSUE THREAD

**Issue by janory** [lightbend/akkaserverless-javascript-sdk#15]
Similar to [actions](https://github.com/lightbend/akkaserverless-framework/issues/391) we need to support asynchronous handlers for entities as well.

Callback/Promised based programming in the JS/TS world is very common, we need to support this functionality for entities as well.
See more about the use cases and reasons [here](https://github.com/lightbend/akkaserverless/discussions/4136).

**Comment by janory** [comment]
fyi @pvlugter

**Comment by ennru** [comment]
Fixed with #43
