### ISSUE TITLE
Incorrectly generated package-lock.json file in the sdk

### ISSUE THREAD

**Issue by janory** [lightbend/akkaserverless-javascript-sdk#154]
### Issue
The current version in master incorrectly assumes that we are using [NPM 7](https://github.com/lightbend/akkaserverless-javascript-sdk/blob/59320f2a314e8de68e75d66f653b28cf6e592d3f/sdk/package-lock.json#L4).

Another issue is that the `packages` [section](https://github.com/lightbend/akkaserverless-javascript-sdk/blob/59320f2a314e8de68e75d66f653b28cf6e592d3f/sdk/package-lock.json#L6) probably shouldn't be part of the versioned `package-lock.json` file, because it's always decided/generated during packaging time.

### Solution
Regenerate the `package-lock.json` with NPM 6, without the `packages` section.

**Comment by pvlugter** [comment]
Yes, at some point it became package lock version 2 (back in #19). Agree that it would be better using npm 6 while we're using node 14. We decided to just leave it, and use node 14 with npm 7 when updating it, but I also think it would be easier to convert back.
