### ISSUE TITLE
Include TypeScript snippets alongside the JavaScript snippets in the documentations

### ISSUE THREAD

**Issue by janory** [lightbend/akkaserverless-javascript-sdk#174]

**Comment by beritou** [comment]
This is a great idea. What do you imagine it would look like?

I like how the Akka docs have separate tabs for Scala & Java. Not sure how much effort this would be in Akka Serverless docs.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/6062111/133310601-5c574afe-bedb-41ed-aebd-a9d0752f0401.png">

https://doc.akka.io/docs/akka/current/typed/actors.html#first-example

**Comment by retgits** [comment]
That's indeed what we're planning :)

**Comment by janory** [comment]
@beritou This is exactly how I've implemented it. There will be two separate tabs van for JS and one for TS.

**Comment by beritou** [comment]
Excellent
