### ISSUE TITLE
Some links in JavaScript section of docs are broken

### ISSUE THREAD

**Issue by beritou** [lightbend/akkaserverless-javascript-sdk#177]
Credit to @janory for originally discovering the problem

#### Examples of broken links

- On https://developer.lightbend.com/docs/akka-serverless/javascript/index.html
  - [support tiers](https://developer.lightbend.com/docs/akka-serverless/developing/sdk-support.html) link is broken
  - [example applications](https://developer.lightbend.com/docs/akka-serverless/tutorial/index.html)
- On https://developer.lightbend.com/docs/akka-serverless/developing/development-process-js.html#_deploy_to_akka_serverless
  - All 3 links are broken

**Comment by beritou** [comment]
In https://github.com/beritou/akkaserverless-javascript-sdk/tree/link-check I have automated link checking back in place.

There are 15-20 broken links in total. Some are easy to resolve. Others do not have an obvious place to redirect to. Some do not have any place to redirect to at all.

**Comment by retgits** [comment]
Can you share those? I can help you with the links

**Comment by beritou** [comment]
> Can you share those? I can help you with the links

Thank you for the offer. I pinged you at various places in my [PR](https://github.com/lightbend/akkaserverless-javascript-sdk/pull/176). 😄

**Comment by retgits** [comment]
I noticed 😂
