### ISSUE TITLE
Install module doc snippet incorrect

### ISSUE THREAD

**Issue by johanandren** [lightbend/akkaserverless-javascript-sdk#196]
Docs here https://developer.lightbend.com/docs/akka-serverless/javascript/index.html#_add_sdk_libraries says `npm install akkaserverless@0.33.1 --save-exact` but that's not right.

`npm install @lightbend/akkaserverless-javascript-sdk --save-exact` works but I don't know how to get the specific sdk version in there, adding another `@0.33.1` gives me an error

**Comment by johanandren** [comment]
Scrap that last part, including the version works.

**Comment by pvlugter** [comment]
Fixed by #197
