### ISSUE TITLE
Codegen executable not found (404 not found)

### ISSUE THREAD

**Issue by StevePavlin** [lightbend/akkaserverless-javascript-sdk#263]
Pleasantly surprised to hear of Akka coming to JavaScript. After following the guide "Kickstart a Node module", I'm blocked at the following part due to a 404 of the codegen package:

![image](https://user-images.githubusercontent.com/8277473/159809737-ba11229c-cf8e-4c66-aed3-e5e3745ab466.png)

Any idea if the CDN is incorrect? I confirmed this is working on my Linux box, but is a problem on my Windows machine.

**Comment by jroper** [comment]
Fixed in #264.
