### ISSUE TITLE
Initial testkit still refers to Event Sourced Entity

### ISSUE THREAD

**Issue by rstento** [lightbend/akkaserverless-javascript-sdk#75]
In testkit.js: /**
 * Mocks the behaviour of a single Akka Serverless Event-sourced entity.
 *
 * Handles any commands and events, internally tracking the state and maintaining an event log.
 *
 * NOTE: Entity IDs are not handled, so all commands are assumed to refer to a single entity.
 */

Which is confusing because its now generating a counter Value Entity

**Comment by ennru** [comment]
Closing historic issue.
